version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${SECRET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SECRET_POSTGRES_PASSWORD}